### PR TITLE
Also check if node is not A.Node since other libraries may be appending getDOMNode

### PR DESCRIPTION
**Pull request by antoniopol06**

### CODE REVIEW

**Comment by juangon** [comment]
Hi @jonmak08 FYI this should fix an error in Alloy Editor when adding a table (https://issues.liferay.com/browse/LPS-62525).
Thanks very much!

**Comment by jonmak08** [comment]
Hey @antoniopol06 and @juangon,

I will review this tomorrow morning and push this in.  Sorry for the delay.

Please let me know if you have any questions. Thanks!

**Comment by antoniopol06** [comment]
@jonmak08 thanks!

**Comment by jonmak08** [comment]
Merged and pushed.

https://github.com/liferay/yui3/commits/patched-v3.18.1

**Pull request closed without merging**
