### PR TITLE
AUI-3185 Add trasnlations to calendar aria labels

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @jonmak08 

I've check other pr and I've replicate them.

Anyway, this is the first time I've patch the YUI repo, so if you see something wrong, please tell me. 

I havent test it yet (I have to check how to build all the small pieces - Yui -> Alloy -> frontend bundle, so if you see something, do not merge it - BTW, any help will be apreciated ;) .

Regards!!

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @robertoDiaz,

A few questions about this.  Should we include all the languages that are translated in calendar or do we only care about the 3 that you submitted?

```
 "lang" : [
            "ca",
            "ca-ES",
            "de",
            "en",
            "es",
            "es-AR",
            "eu-ES",
            "fr",
            "hu",
            "it",
            "ja",
            "nb-NO",
            "nl",
            "pt-BR",
            "ru",
            "zh-Hans",
            "zh-Hans-CN",
            "zh-Hant",
            "zh-Hant-HK",
            "zh-HANT-TW"
        ],
```

Also, the ones that you submitted (`en`, `es-ES`, and `es-EU`) are different than what is currently translated in calendar.  We have (`en`, `es`, and `eu-ES`) in calendar.

Please advise on what languages codes we should be using.  Thanks!

**Comment by jonmak08** [comment]
Also, in order to build this, we need to add the languages we want to build into the `calendarnavigator.json` file.

```
        "lang" : [
            "en",
            "es-ES",
            "es-EU"
        ],
```

**Comment by robertoDiaz** [comment]
For the current case, the customer only needs this languajes.

Since I do not know the translation process of this repo, I didn't add more translations to it.

> Also, in order to build this, we need to add the languages we want to build into the `calendarnavigator.json` file.
> 
> ```
>         "lang" : [
>             "en",
>             "es-ES",
>             "es-EU"
>         ],
> ```

This is a Typo, "es-EU" should be eu-ES

**Comment by jonmak08** [comment]
> For the current case, the customer only needs this languajes.
> This is a Typo, "es-EU" should be eu-ES

OK I will update with all the languages from `calendar` to match just in case and make a new release of YUI.

Thanks!

**Comment by jonmak08** [comment]
Hey @robertoDiaz,

I was looking at what you submitted and I am trying to figure out which aria labels you are talking about that need translating?  Is the highlighted ones in the picture below what are you talking about?

YUI/AUI:
image

Liferay Portal:
image

If so, we need to add the translations and update the code at https://github.com/liferay/yui3/blob/patched-v3.18.1/src/calendar/js/calendarnavigator.js#L277.L278 to be similar to https://github.com/liferay/yui3/blob/patched-v3.18.1/src/calendar/js/calendar-base.js#L1081...L1085.

Also, can you update https://issues.liferay.com/browse/AUI-3185 with steps for testing the issue for QA?

Please let me know if you have any questions. Thanks!

**Comment by robertoDiaz** [comment]
Yes theese are the buttons.

Ok, I'll update the pr with this changes.

I'll try to do this tomorrow

**Comment by jonmak08** [comment]
Thanks @robertoDiaz!  I will close this pull request for now.

Please let me know if you have any questions.  Thanks!

**Pull request closed without merging**
