### PR TITLE
AUI-3097 Move fix outside of subs conditional so code is actually rea…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…ched at the proper time.

As noted on the ticket in JIRA, I'm resending the PR for this fix because I had placed the fix in the wrong location initially and therefor the code never executed.  If you notice any issues with the change for this, please notify me and I'll get to work immediately trying to fix them.

### CODE REVIEW

**Comment by gregory-bretall** [comment]
Any update on this @jonmak08?  Thanks in advance.

**Comment by jonmak08** [comment]
Hey @gregory-bretall,

Sorry for the delay, I started reviewing this and I think we need to update the unit test somehow.  Because the original fix was wrong, I feel like the unit test should fail under those circumstances, but with these changes, the unit test should pass.

After reviewing the unit test, we are not really doing much other than checking to see if there is a root language file for the module and if there is, it will pass.  I feel like the unit test should test functionality that we are adding.

For example, if someone were to use any language that was not defined, we should have it fall back to using the root language rather than forcefully passing in ```''``` into the call ```loader.getLangPackName('', 'datatable-sort');```

I am not sure if that clarifies everything, but just my thoughts based on the changes.

**Comment by gregory-bretall** [comment]
Thanks for taking a look at this @jonmak08, I should be able to fix up the unit test some time tomorrow and I can then update the branch with a commit for the fixed unit test.  Let me know if there were any other changes you think needed to be made.

**Comment by jonmak08** [comment]
Hey @gregory-bretall,

I think that was the only thing that kept me from merging the pull.  Thanks!  Just let me know when you update this unit test, and I will review the pull.  Thanks!

**Comment by jonmak08** [comment]
Closing pull request because unit test changes are still waiting.  Please reopen or submit another pull request when changes are completed.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
