### PR TITLE
AUI-2063 Remove autogenerated id

### PR DESCRIPTION
**Pull request by ericyanLr**
Hey @jonmak08,

This pull request is for backporting [AUI-2063](https://issues.liferay.com/browse/AUI-2063) to 62x.
I was able to cleanly cherry-pick the fix from patched-v3.18.1 to patched-v3.11.0.
**Note:** I did not include the Build commit, only the code changes.

Also, I created [BPR-5129](https://issues.liferay.com/browse/BPR-5129) for the backport.
For future reference, do I need to reference this pull request link to any of the tickets (AUI/BPR/LPS)?

Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

View just my changes: https://github.com/jonmak08/yui3/compare/ericyanLr:df63d653f6...2b94ef7545
View total diff: https://github.com/jonmak08/yui3/compare/795439184a...2b94ef7545

**Comment by jonmak08** [comment]
Hey @ericyanLr,

In the future, you can reference this pull request in the AUI ticket.  Just set it as the Github Pull Request link when you create a "Code Review Request".

Please let me know if you have any questions.  Thanks!

**Comment by ericyanLr** [comment]
Hey @jonmak08,

When you reference AUI ticket, do you mean the original [AUI-2063](https://issues.liferay.com/browse/AUI-2063)? 
If so, would I have to re-open the ticket to make a Code Review Request?

Thanks!

**Comment by jonmak08** [comment]
Yup, you would reopen the original ticket ([AUI-2063](https://issues.liferay.com/browse/AUI-2063)) and make a Code Review Request on that.

That is how I do it with ee-6.2.x backports.  I always reopen the original LPS ticket and submit a Code Review Request against it.  The BPR is just for the support team to track the fixes for the fixpacks.

**Comment by ericyanLr** [comment]
I see, thanks for answering my questions. I will do that for future AUI backports!

**Comment by jonmak08** [comment]
Thanks @ericyanLr!

**Pull request merged**
